// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/room': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/room.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/room.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/room.post').default>>>>
    }
    '/api/rooms': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms.get').default>>>>
    }
    '/api/upload-avatar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload-avatar').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}